"""empty message

Revision ID: 1190fc436fd8
Revises: 70945d58268e
Create Date: 2020-05-27 13:41:26.646293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1190fc436fd8'
down_revision = '70945d58268e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artistGenre', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'artistGenre', 'genre', ['genre_id'], ['id'])
    op.add_column('venueGenre', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venueGenre', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venueGenre', type_='foreignkey')
    op.drop_column('venueGenre', 'genre_id')
    op.drop_constraint(None, 'artistGenre', type_='foreignkey')
    op.drop_column('artistGenre', 'genre_id')
    # ### end Alembic commands ###
